Sidebar
krstem/VatBox_AccountSetup_Task pull request #2
Opened 2019-08-20 09:14 UTC by aatanasova

2019-08-20 14:40 UTC, sweko requested changes

2019-08-20 14:40 UTC, sweko commented on src/components/Sidebar.js
> +  const VatRecovery = [
Extract to `constants` file

2019-08-20 14:40 UTC, sweko commented on src/components/Sidebar.js
> +                            Evidance Qualification
change spelling

2019-08-20 14:40 UTC, sweko commented on src/components/Sidebar.js
> +   const TAXTailor = [
Change casing

2019-08-20 14:40 UTC, sweko commented on src/stylesheets/sidebar.scss
> +    text-align: left !important;
do we need `!important`

2019-08-21 08:23 UTC, aatanasova commented on src/components/Sidebar.js
> +                            Evidance Qualification
Fixed

2019-08-21 08:23 UTC, aatanasova commented on src/components/Sidebar.js
> +   const TAXTailor = [
Fixed

2019-08-21 08:24 UTC, aatanasova commented on src/stylesheets/sidebar.scss
> +    text-align: left !important;
Fixed

2019-08-21 08:27 UTC, aatanasova commented on src/components/Sidebar.js
> +  const VatRecovery = [
Fixed

2019-08-21 13:00 UTC, sweko approved these changes

2019-08-21 13:08 UTC, merged